i<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>sol</string>
    </array>
    <key>name</key>
    <string>Solidity</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#natspec</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operator</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#control</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constant</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#number</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#global</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function-call</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#assembly</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuation</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>natspec</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.solidity</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#natspec-tags</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>///</string>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.block.documentation.solidity</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#natspec-tags</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>natspec-tags</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#natspec-tag-title</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#natspec-tag-author</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#natspec-tag-notice</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#natspec-tag-dev</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#natspec-tag-param</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#natspec-tag-return</string>
          </dict>
        </array>
      </dict>
      <key>natspec-tag-title</key>
      <dict>
        <key>match</key>
        <string>(@title)\b</string>
        <key>name</key>
        <string>storage.type.title.natspec</string>
      </dict>
      <key>natspec-tag-author</key>
      <dict>
        <key>match</key>
        <string>(@author)\b</string>
        <key>name</key>
        <string>storage.type.author.natspec</string>
      </dict>
      <key>natspec-tag-notice</key>
      <dict>
        <key>match</key>
        <string>(@notice)\b</string>
        <key>name</key>
        <string>storage.type.dev.natspec</string>
      </dict>
      <key>natspec-tag-dev</key>
      <dict>
        <key>match</key>
        <string>(@dev)\b</string>
        <key>name</key>
        <string>storage.type.dev.natspec</string>
      </dict>
      <key>natspec-tag-param</key>
      <dict>
        <key>match</key>
        <string>(@param)(\s+([A-Za-z_]\w*))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.param.natspec</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.natspec</string>
          </dict>
        </dict>
      </dict>
      <key>natspec-tag-return</key>
      <dict>
        <key>match</key>
        <string>(@return)\b</string>
        <key>name</key>
        <string>storage.type.return.natspec</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-line</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
        </array>
      </dict>
      <key>comment-line</key>
      <dict>
        <key>match</key>
        <string>(?&lt;!tp:)//.*?$</string>
        <key>name</key>
        <string>comment.line.solidity</string>
      </dict>
      <key>comment-block</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.solidity</string>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#operator-logic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator-mapping</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator-arithmetic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator-binary</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator-assignment</string>
          </dict>
        </array>
      </dict>
      <key>operator-logic</key>
      <dict>
        <key>match</key>
        <string>(==|&lt;(?!&lt;)|&lt;=|&gt;(?!&gt;)|&gt;=|\&amp;\&amp;|\|\||\:(?!=)|\?)</string>
        <key>name</key>
        <string>keyword.operator.logic.solidity</string>
      </dict>
      <key>operator-mapping</key>
      <dict>
        <key>match</key>
        <string>(=&gt;)</string>
        <key>name</key>
        <string>keyword.operator.mapping.solidity</string>
      </dict>
      <key>operator-arithmetic</key>
      <dict>
        <key>match</key>
        <string>(\+|\-|\/|\*)</string>
        <key>name</key>
        <string>keyword.operator.arithmetic.solidity</string>
      </dict>
      <key>operator-binary</key>
      <dict>
        <key>match</key>
        <string>(\^|\&amp;|\||&lt;&lt;|&gt;&gt;)</string>
        <key>name</key>
        <string>keyword.operator.binary.solidity</string>
      </dict>
      <key>operator-assignment</key>
      <dict>
        <key>match</key>
        <string>(\:?=)</string>
        <key>name</key>
        <string>keyword.operator.assignment.solidity</string>
      </dict>
      <key>control</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#control-flow</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#control-using</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#control-import</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#control-pragma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#control-underscore</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#control-other</string>
          </dict>
        </array>
      </dict>
      <key>control-flow</key>
      <dict>
        <key>match</key>
        <string>\b(if|else|for|while|do|break|continue|throw|returns?)\b</string>
        <key>name</key>
        <string>keyword.control.flow.solidity</string>
      </dict>
      <key>control-using</key>
      <dict>
        <key>match</key>
        <string>\b(using)\b</string>
        <key>name</key>
        <string>keyword.control.using.solidity</string>
      </dict>
      <key>control-import</key>
      <dict>
        <key>match</key>
        <string>\b(import)\b</string>
        <key>name</key>
        <string>keyword.control.import.solidity</string>
      </dict>
      <key>control-pragma</key>
      <dict>
        <key>match</key>
        <string>\b(pragma)(?:\s+([A-Za-z_]\w+)\s+([^\s]+))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.pragma.solidity</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.pragma.solidity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.other.pragma.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>control-underscore</key>
      <dict>
        <key>match</key>
        <string>\b(_)\b</string>
        <key>name</key>
        <string>constant.other.underscore.solidity</string>
      </dict>
      <key>control-other</key>
      <dict>
        <key>match</key>
        <string>\b(new|delete|emit)\b</string>
        <key>name</key>
        <string>keyword.control.solidity</string>
      </dict>
      <key>constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constant-boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-time</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-currency</string>
          </dict>
        </array>
      </dict>
      <key>constant-boolean</key>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b</string>
        <key>name</key>
        <string>constant.language.boolean.solidity</string>
      </dict>
      <key>constant-time</key>
      <dict>
        <key>match</key>
        <string>\b(seconds|minutes|hours|days|weeks|years)\b</string>
        <key>name</key>
        <string>constant.language.time.solidity</string>
      </dict>
      <key>constant-currency</key>
      <dict>
        <key>match</key>
        <string>\b(ether|wei|finney|szabo)\b</string>
        <key>name</key>
        <string>constant.language.currency.solidity</string>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#number-decimal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number-hex</string>
          </dict>
        </array>
      </dict>
      <key>number-decimal</key>
      <dict>
        <key>match</key>
        <string>\b(\d+(\.\d+)?)\b</string>
        <key>name</key>
        <string>constant.numeric.decimal.solidity</string>
      </dict>
      <key>number-hex</key>
      <dict>
        <key>match</key>
        <string>\b(0[xX][a-fA-F0-9]+)\b</string>
        <key>name</key>
        <string>constant.numeric.hexadecimal.solidity</string>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\".*?\"</string>
            <key>name</key>
            <string>string.quoted.double.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\'.*?\'</string>
            <key>name</key>
            <string>string.quoted.single.solidity</string>
          </dict>
        </array>
      </dict>
      <key>type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-primitive</string>
          </dict>
        </array>
      </dict>
      <key>type-primitive</key>
      <dict>
        <key>match</key>
        <string>\b(address|string\d*|bytes\d*|int\d*|uint\d*|bool|hash\d*)\b</string>
        <key>name</key>
        <string>support.type.primitive.solidity</string>
      </dict>
      <key>global</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#global-variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#global-functions</string>
          </dict>
        </array>
      </dict>
      <key>global-variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(msg|block|tx|now)\b</string>
            <key>name</key>
            <string>variable.language.transaction.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(this)\b</string>
            <key>name</key>
            <string>variable.language.this.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(super)\b</string>
            <key>name</key>
            <string>variable.language.super.solidity</string>
          </dict>
        </array>
      </dict>
      <key>global-functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(require|assert|revert)\b</string>
            <key>name</key>
            <string>keyword.control.exceptions.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(selfdestruct|suicide)\b</string>
            <key>name</key>
            <string>keyword.control.contract.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(addmod|mulmod|keccak256|sha256|sha3|ripemd160|ecrecover)\b</string>
            <key>name</key>
            <string>support.function.math.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(blockhash|gasleft)\b</string>
            <key>name</key>
            <string>variable.language.transaction.solidity</string>
          </dict>
        </array>
      </dict>
      <key>declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#declaration-contract</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-interface</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-library</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-struct</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-event</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-enum</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-constructor</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-modifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration-mapping</string>
          </dict>
        </array>
      </dict>
      <key>declaration-contract</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(contract)(\s+([A-Za-z_]\w*))?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.contract.solidity</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.contract.solidity</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(is)\b</string>
            <key>name</key>
            <string>storage.modifier.is.solidity</string>
          </dict>
        </array>
      </dict>
      <key>declaration-interface</key>
      <dict>
        <key>match</key>
        <string>\b(interface)(\s+([A-Za-z_]\w*))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.interface.solidity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.interface.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>declaration-library</key>
      <dict>
        <key>match</key>
        <string>\b(library)(\s+([A-Za-z_]\w*))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.library.solidity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.library.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>declaration-struct</key>
      <dict>
        <key>match</key>
        <string>\b(struct)(\s+([A-Za-z_]\w*))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.struct.solidity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.struct.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>declaration-event</key>
      <dict>
        <key>match</key>
        <string>\b(event)(\s+([A-Za-z_]\w*))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.event.solidity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.event.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>declaration-constructor</key>
      <dict>
        <key>match</key>
        <string>\b(constructor)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.constructor.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>declaration-enum</key>
      <dict>
        <key>match</key>
        <string>\b(enum)(\s+([A-Za-z_]\w*))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.enum.solidity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.enum.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>declaration-function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(function)\s+([A-Za-z_]\w*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.solidity</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.solidity</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(private|public|internal|external|constant|immutable|pure|view|payable|nonpayable|inherited|indexed|storage|memory|virtual|calldata|override|abstract)\b</string>
            <key>name</key>
            <string>storage.type.mofifier.solidity</string>
          </dict>
        </array>
      </dict>
      <key>declaration-modifier</key>
      <dict>
        <key>match</key>
        <string>\b(modifier)(\s+([A-Za-z_]\w*))?\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.modifier.solidity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>declaration-mapping</key>
      <dict>
        <key>match</key>
        <string>\b(mapping)\b</string>
        <key>name</key>
        <string>storage.type.mapping.solidity</string>
      </dict>
      <key>function-call</key>
      <dict>
        <key>match</key>
        <string>\b([A-Za-z_]\w*)\s*\(</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.solidity</string>
          </dict>
        </dict>
      </dict>
      <key>assembly</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(assembly)\b</string>
            <key>name</key>
            <string>keyword.control.assembly.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(let)\b</string>
            <key>name</key>
            <string>storage.type.assembly.solidity</string>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.terminator.statement.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>punctuation.accessor.solidity</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.solidity</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.solidity</string>
    <key>uuid</key>
    <string>ad87d2cd-8575-4afe-984e-9421a3788933</string>
  </dict>
</plist>
